Wire up timestamp support
This commit wires up ion-hash to the newly factored binary/timestamp.rs
encoder. We copy over the tests from the suite. They fail:

```
thread 'ion_hash_tests' panicked at 'assertion failed: `(left == right)`
  left: `[11, 96, 192, 15, 225, 14]`,
 right: `[11, 96, 99, 128, 15, 225, 14]`: test case 2017T failed', ion-hash\tests\ion_hash_tests.rs:152:5
```

Turns out there were two bugs related to offsets in ion-rust. Those are
now fixed!

The binary timestamp tests (10n) are not part of this commit because
they require a bit more machinery.